- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
      - check-requirements
    check:
      jobs:
        # TripleO jobs that deploy Barbican.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario002-multinode-oooq-container will
        # run in Pike and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container:
            voting: false
        - openstack-tox-cover:
            voting: false
        - octavia-v1-dsvm-scenario:
            voting: false
    gate:
      queue: barbican
